[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd ../../ && npm install"]

[phases.build]
cmds = ["cd ../../ && npm run build --prefix apps/web"]

[variables]
NIXPACKS_STATIC_DIR = "apps/web/dist"
