[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
# installer au niveau racine pour r√©soudre workspace:* (monorepo)
cmds = ["cd .. && cd .. && npm install"]

[phases.build]
# build via la racine
cmds = ["cd .. && cd .. && npm run build --prefix apps/api"]

[start]
cmd = "node dist/server.js"
